inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'data/**/*'
    - 'vendor/**/*'

Metrics/CollectionLiteralLength:
  Exclude:
    - 'lib/paygate/aes.rb'

Naming/FileName:
  Exclude:
    - 'lib/paygate-ruby.rb'

Naming/MethodParameterName:
  Exclude:
    - 'lib/paygate/aes.rb'
    - 'lib/paygate/aes_ctr.rb'

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self
